export class fontStyle{
    static fontStyles = [
        {
          "id": 2,
          "name": "Alegreya",
          "title": "Alegreya",
          "preview_file_id": 46176,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700,800",
          "italic_ind": 1,
          "url": "files/fonts/alegreya.jpg"
        },
        {
          "id": 27,
          "name": "Anton",
          "title": "Anton",
          "preview_file_id": 46177,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/anton.jpg"
        },
        {
          "id": 25,
          "name": "Archivo",
          "title": "Archivo",
          "preview_file_id": 46180,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,500",
          "italic_ind": 1,
          "url": "files/fonts/archivo.jpg"
        },
        {
          "id": 23,
          "name": "Archivo Black",
          "title": "Archivo Black",
          "preview_file_id": 46178,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/archivo_black.jpg"
        },
        {
          "id": 24,
          "name": "Archivo Narrow",
          "title": "Archivo Narrow",
          "preview_file_id": 46179,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,500",
          "italic_ind": 1,
          "url": "files/fonts/archivo_narrow.jpg"
        },
        {
          "id": 3,
          "name": "Armata",
          "title": "Armata",
          "preview_file_id": 46181,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/armata.jpg"
        },
        {
          "id": 4,
          "name": "Bubblegum Sans",
          "title": "Bubblegum Sans",
          "preview_file_id": 46182,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/bubblegum_sans.jpg"
        },
        {
          "id": 35,
          "name": "Bungee",
          "title": "Bungee",
          "preview_file_id": 46183,
          "status": "Active",
          "source": "Google",
          "keywords": "",
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/bungee.jpg"
        },
        {
          "id": 5,
          "name": "Cambo",
          "title": "Cambo",
          "preview_file_id": 46184,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/cambo.jpg"
        },
        {
          "id": 40,
          "name": "Lobster",
          "title": "Cape Code",
          "preview_file_id": 49908,
          "status": "Active",
          "source": "Google",
          "keywords": "Lobster Font, Cape Cod Font",
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/lobster.jpg"
        },
        {
          "id": 6,
          "name": "Carter One",
          "title": "Carter One",
          "preview_file_id": 46186,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/carter_one.jpg"
        },
        {
          "id": 30,
          "name": "Caveat Brush",
          "title": "Caveat Brush",
          "preview_file_id": 46187,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 0,
          "url": "files/fonts/caveat_brush.jpg"
        },
        {
          "id": 42,
          "name": "Courgette",
          "title": "Courgette",
          "preview_file_id": 46876,
          "status": "Active",
          "source": "Google",
          "keywords": "Courgette",
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/courgette.jpg"
        },
        {
          "id": 7,
          "name": "Crete Round",
          "title": "Crete Round",
          "preview_file_id": 46188,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 1,
          "url": "files/fonts/crete_round.jpg"
        },
        {
          "id": 32,
          "name": "Cutive",
          "title": "Cutive",
          "preview_file_id": 46189,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/cutive.jpg"
        },
        {
          "id": 8,
          "name": "Days One",
          "title": "Days One",
          "preview_file_id": 46190,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/days_one.jpg"
        },
        {
          "id": 9,
          "name": "Fanwood Text",
          "title": "Fanwood Text",
          "preview_file_id": 46191,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 1,
          "url": "files/fonts/fanwood_text.jpg"
        },
        {
          "id": 10,
          "name": "Fredoka One",
          "title": "Fredoka One",
          "preview_file_id": 47577,
          "status": "Active",
          "source": "Google",
          "keywords": "",
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/fredoka-one.jpg"
        },
        {
          "id": 11,
          "name": "Gentium Basic",
          "title": "Gentium Basic",
          "preview_file_id": 47628,
          "status": "Active",
          "source": "Google",
          "keywords": "",
          "weights": "400,700",
          "italic_ind": 1,
          "url": "files/fonts/gentium-basic.jpg"
        },
        {
          "id": 34,
          "name": "Graduate",
          "title": "Graduate",
          "preview_file_id": 46194,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 0,
          "url": "files/fonts/graduate.jpg"
        },
        {
          "id": 36,
          "name": "Grand Hotel",
          "title": "Grand Hotel",
          "preview_file_id": 46195,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/grand_hotel.jpg"
        },
        {
          "id": 12,
          "name": "Great Vibes",
          "title": "Great Vibes",
          "preview_file_id": 46196,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/great_vibes.jpg"
        },
        {
          "id": 38,
          "name": "Hammersmith One",
          "title": "Hammersmith One",
          "preview_file_id": 46197,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/hammersmith_one.jpg"
        },
        {
          "id": 13,
          "name": "Knewave",
          "title": "Knewave",
          "preview_file_id": 46198,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/knewave.jpg"
        },
        {
          "id": 14,
          "name": "Linden Hill",
          "title": "Linden Hill",
          "preview_file_id": 46199,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 1,
          "url": "files/fonts/linden_hill.jpg"
        },
        {
          "id": 15,
          "name": "Michroma",
          "title": "Michroma",
          "preview_file_id": 46200,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/michroma.jpg"
        },
        {
          "id": 1,
          "name": "Montserrat",
          "title": "Montserrat",
          "preview_file_id": 46201,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,500,700,900",
          "italic_ind": 1,
          "url": "files/fonts/montserrat.jpg"
        },
        {
          "id": 16,
          "name": "Open Sans",
          "title": "Open Sans",
          "preview_file_id": 49914,
          "status": "Active",
          "source": "Google",
          "keywords": "",
          "weights": "400,600,700,800",
          "italic_ind": 1,
          "url": "files/fonts/open-sans.jpg"
        },
        {
          "id": 17,
          "name": "Oswald",
          "title": "Oswald",
          "preview_file_id": 46203,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 0,
          "url": "files/fonts/oswald.jpg"
        },
        {
          "id": 18,
          "name": "Pacifico",
          "title": "Pacifico",
          "preview_file_id": 46204,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/pacifico.jpg"
        },
        {
          "id": 28,
          "name": "Palanquin",
          "title": "Palanquin",
          "preview_file_id": 46206,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "300,400,500,700",
          "italic_ind": 0,
          "url": "files/fonts/palanquin.jpg"
        },
        {
          "id": 29,
          "name": "Palanquin Dark",
          "title": "Palanquin Dark",
          "preview_file_id": 46205,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 0,
          "url": "files/fonts/palanquin_dark.jpg"
        },
        {
          "id": 26,
          "name": "Patua One",
          "title": "Patua One",
          "preview_file_id": 46207,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 1,
          "url": "files/fonts/patua_one.jpg"
        },
        {
          "id": 39,
          "name": "PT Sans",
          "title": "PT Sans",
          "preview_file_id": 46208,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 1,
          "url": "files/fonts/pt_sans.jpg"
        },
        {
          "id": 37,
          "name": "Rammetto One",
          "title": "Rammetto One",
          "preview_file_id": 46209,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/rammetto_one.jpg"
        },
        {
          "id": 41,
          "name": "Roboto",
          "title": "Roboto",
          "preview_file_id": 46210,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "300,400,700",
          "italic_ind": 1,
          "url": "files/fonts/roboto.jpg"
        },
        {
          "id": 33,
          "name": "Schoolbell",
          "title": "Schoolbell",
          "preview_file_id": 46211,
          "status": "Active",
          "source": "Google",
          "keywords": "",
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/schoolbell.jpg"
        },
        {
          "id": 19,
          "name": "Signika",
          "title": "Signika",
          "preview_file_id": 46212,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,700",
          "italic_ind": 0,
          "url": "files/fonts/signika.jpg"
        },
        {
          "id": 20,
          "name": "Sniglet",
          "title": "Sniglet",
          "preview_file_id": 46213,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400,800",
          "italic_ind": 0,
          "url": "files/fonts/sniglet.jpg"
        },
        {
          "id": 21,
          "name": "Sofia",
          "title": "Sofia",
          "preview_file_id": 46214,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/sofia.jpg"
        },
        {
          "id": 43,
          "name": "Special Elite",
          "title": "Special Elite",
          "preview_file_id": 48040,
          "status": "Active",
          "source": "Google",
          "keywords": "Special Elite, font",
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/special-elite.jpg"
        },
        {
          "id": 22,
          "name": "Ubuntu",
          "title": "Ubuntu",
          "preview_file_id": 46215,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "300,500,700",
          "italic_ind": 1,
          "url": "files/fonts/ubuntu.jpg"
        },
        {
          "id": 31,
          "name": "Yesteryear",
          "title": "Yesteryear",
          "preview_file_id": 46216,
          "status": "Active",
          "source": "Google",
          "keywords": null,
          "weights": "400",
          "italic_ind": 0,
          "url": "files/fonts/yesteryear.jpg"
        }
      ]
}